import { readFileSync, writeFileSync } from "node:fs";

const html = readFileSync(new URL("../dist/index.html", import.meta.url), "utf8");

const scriptOpenIdx = html.indexOf("<script");
const scriptTagEnd = html.indexOf(">", scriptOpenIdx) + 1;
const scriptCloseIdx = html.lastIndexOf("</script>");
const scriptContent = html.slice(scriptTagEnd, scriptCloseIdx);

const styleOpenIdx = html.indexOf("<style");
const styleTagEnd = html.indexOf(">", styleOpenIdx) + 1;
const styleCloseIdx = html.indexOf("</style>", styleTagEnd);
const styleContent = html.slice(styleTagEnd, styleCloseIdx);

const skeleton =
  html.slice(0, scriptOpenIdx) +
  html.slice(scriptCloseIdx + "</script>".length, styleOpenIdx) +
  html.slice(styleCloseIdx + "</style>".length);

const out = `// Generated by scripts/build-embed.mjs from dist/index.html (vite-plugin-singlefile
// build) — do not hand-edit. Draft Punk's AIUX static host only serves image/font
// files from public/, not .html/.css/.js, so this self-contained bundle is inlined
// as strings and mounted via iframe.srcdoc in pages/handwave/page.js.
export const HANDWAVE_HTML = ${JSON.stringify(skeleton)};
export const HANDWAVE_CSS = ${JSON.stringify(styleContent)};
export const HANDWAVE_JS = ${JSON.stringify(scriptContent)};
`;

writeFileSync(new URL("../handwave-embed.js", import.meta.url), out);
console.log("wrote client/handwave-embed.js", {
  htmlLen: skeleton.length,
  cssLen: styleContent.length,
  jsLen: scriptContent.length,
});
